import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import React from "react";
import { Providers } from "./providers";
import UserMenu from "@/components/UserMenu";

const inter = Inter({
  variable: "--font-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="scroll-smooth">
      <body className={`${inter.variable} antialiased motion-ok`}>
        <Providers>
          <UserMenu />
          {/* global hero background on every page */}
          <div className="hero-background fixed inset-0 -z-10 pointer-events-none" aria-hidden="true">
            <div className="hero-lights w-full h-full" />
          </div>
          {children}
        </Providers>
      </body>
    </html>
  );
}
